export default {
  "a": "Link",
  "abbr": "Abbreviation",
  "acronym": "Acronym (Deprecated)",
  "address": "Address",
  "area": "Image Map Area",
  "article": "Article",
  "aside": "Aside",
  "audio": "Audio",
  "b": "Bold Text",
  "base": "Base URL",
  "bdi": "Bidirectional Isolation",
  "bdo": "Bidirectional Override",
  "big": "Big Text (Deprecated)",
  "blockquote": "Block Quote",
  "body": "Body",
  "br": "Line Break",
  "button": "Button",
  "canvas": "Canvas",
  "caption": "Caption",
  "center": "Centered Text (Deprecated)",
  "cite": "Citation",
  "code": "Code",
  "col": "Table Column",
  "colgroup": "Column Group",
  "data": "Data",
  "datalist": "Data List",
  "dd": "Description Detail",
  "del": "Deleted Text",
  "details": "Details",
  "dfn": "Definition",
  "dialog": "Dialog",
  "dir": "Directory List (Deprecated)",
  "div": "Division",
  "dl": "Description List",
  "dt": "Description Term",
  "em": "Emphasis",
  "embed": "Embedded Content",
  "fencedframe": "Fenced Frame",
  "fieldset": "Fieldset",
  "figcaption": "Figure Caption",
  "figure": "Figure",
  "font": "Font (Deprecated)",
  "footer": "Footer",
  "form": "Form",
  "frame": "Frame (Deprecated)",
  "frameset": "Frameset (Deprecated)",
  "geolocation": "Geolocation",
  "h1": "Heading 1",
  "h2": "Heading 2",
  "h3": "Heading 3",
  "h4": "Heading 4",
  "h5": "Heading 5",
  "h6": "Heading 6",
  "head": "Head",
  "header": "Header",
  "hgroup": "Heading Group",
  "hr": "Horizontal Rule",
  "html": "HTML",
  "i": "Icon or Italics (use em instead)",
  "iframe": "iFrame",
  "img": "Image",
  "input": "Input",
  "ins": "Inserted Text",
  "kbd": "Keyboard Input",
  "label": "Label",
  "legend": "Legend",
  "li": "List Item",
  "link": "Resource Import",
  "main": "Main",
  "map": "Image Map",
  "mark": "Highlight",
  "marquee": "Scrolling Text (Deprecated)",
  "menu": "Menu",
  "meta": "Metadata",
  "meter": "Meter",
  "nav": "Navigation",
  "nobr": "No Break (Deprecated)",
  "noembed": "No Embed",
  "noframes": "No Frames",
  "noscript": "No Script",
  "object": "Object",
  "ol": "Ordered List",
  "optgroup": "Option Group",
  "option": "Option",
  "output": "Output",
  "p": "Paragraph",
  "param": "Parameter",
  "picture": "Picture",
  "plaintext": "Plain Text (Deprecated)",
  "pre": "Preformatted Text",
  "progress": "Progress",
  "q": "Quote",
  "rb": "Ruby Base",
  "rp": "Ruby Parentheses",
  "rt": "Ruby Text",
  "rtc": "Ruby Container",
  "ruby": "Ruby Annotation",
  "s": "Strikethrough",
  "samp": "Sample Output",
  "script": "Script",
  "search": "Search",
  "section": "Section",
  "select": "Select",
  "selectedcontent": "Selected Content",
  "slot": "Slot",
  "small": "Small Text",
  "source": "Source",
  "span": "Span",
  "strike": "Strikethrough (Deprecated)",
  "strong": "Strong Importance",
  "style": "Style",
  "sub": "Subscript",
  "summary": "Summary",
  "sup": "Superscript",
  "table": "Table",
  "tbody": "Table Body",
  "td": "Table Cell",
  "template": "Component Template",
  "textarea": "Textarea",
  "tfoot": "Table Footer",
  "th": "Table Header",
  "thead": "Table Head",
  "time": "Time",
  "title": "Title",
  "tr": "Table Row",
  "track": "Track",
  "tt": "Teletype (Deprecated)",
  "u": "Underline (Deprecated)",
  "ul": "Unordered List",
  "var": "Variable",
  "video": "Video",
  "wbr": "Word Break",
  "xmp": "Raw Text (Deprecated)"
}